# Generated by Django 2.2.24 on 2024-06-28 09:56

from django.conf import settings
from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_auto_20240628_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст жалобы')),
                ('user', models.ForeignKey(on_delete=models.SET(property.models.get_sentinel_user), related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался?')),
            ],
        ),
    ]
