# Generated by Django 2.2.24 on 2024-06-28 10:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU'),
        ),
    ]
