# Generated by Django 2.2.24 on 2024-06-28 10:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Нормализованный номер владельца'),
        ),
    ]
