# Generated by Django 2.2.24 on 2024-06-28 11:07

from django.db import migrations
import phonenumbers


def test_phonenumber_parse(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat = Flat.objects.filter(owners_phonenumber='+70000000000').first()
    flat.owner_pure_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
    flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20240628_1346'),
    ]

    operations = [
        migrations.RunPython(test_phonenumber_parse)
    ]
