# Generated by Django 2.2.24 on 2024-06-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phonenumber',
            new_name='pure_phone_number',
        ),
    ]
