# Generated by Django 2.2.24 on 2024-06-28 11:38

from django.db import migrations

from django.db import migrations


def fill_owners_persons(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats_all = Flat.objects.all()
    for flat in flats_all.iterator():
        Owner.objects.get_or_create(full_name=flat.owner, defaults={'phone_number': flat.owners_phonenumber,
                                                                    'pure_phone_number': flat.owner_pure_phonenumber})


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0015_auto_20240628_1437'),
    ]

    operations = [
        migrations.RunPython(fill_owners_persons)
    ]
