# Generated by Django 2.2.24 on 2024-06-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20240628_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='property.Flat', verbose_name='Квартира, которую лайнули'),
        ),
    ]
